sudo: required

before_install:
  - curl -sS https://nixos.org/nix/install | sh
  - source $HOME/.nix-profile/etc/profile.d/nix.sh

install:
  - nix-shell --run 'true'

script:
  - nix-shell --run 'cabal test'
  - nix-shell --run 'bats ./test/funct/test.bats'
  - nix-shell --run 'cabal sdist'
